services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 8080
      APP_CORS_ALLOWED_ORIGINS: "*"
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
