services:
  - type: web
    name: peace-and-love-adroabaa
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8080
      - key: APP_CORS_ALLOWED_ORIGINS
        value: "*"
